name: NametagColorPlugin
version: 1.0.2
main: fr.NametagColorPlugin
description: This plugin uses Bukkit's scoreboard to locally change the name tag color of a player. It was originally created for playing strategic UHCs
author: planetwide!
commands:
  color:
    description: Change the color of a nametag locally.
    usage: /color <player> <color>
    aliases:
      - setcolor
      - playercolor
